version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: fruitGarden_nginx
    ports:
      - "8089:80"
    volumes:
      - ./src:/var/www/html 
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fruitGarden_php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html